/**
 * Domain email sekali-pakai yang ditolak saat pendaftaran.
 *
 * Kenapa ini penting untuk Ketuk.id secara spesifik: akun di sini terhubung ke
 * transaksi uang sungguhan (hadiah dari tamu, pembayaran plan) dan ke link
 * undangan yang dibagikan ke ratusan orang. Kalau email pemiliknya kedaluwarsa
 * dalam 10 menit, tidak ada jalan lagi untuk memulihkan akses akun, mengirim
 * bukti pembayaran, atau menghubungi host saat ada masalah dengan order.
 *
 * Daftar ini sengaja TIDAK diklaim lengkap — domain temp mail baru muncul terus.
 * Ini lapisan pertama yang murah dan menangkap mayoritas kasus; lapisan kedua
 * adalah verifikasi MX record di sisi server (lihat frontend `(auth)/daftar/+page.server.ts`),
 * yang menolak domain yang memang tidak bisa menerima email sama sekali.
 *
 * Pencocokan dilakukan terhadap domain DAN semua induknya, jadi satu entri
 * `mailinator.com` sekaligus menolak `team.mailinator.com` dan seterusnya.
 */
export const DISPOSABLE_EMAIL_DOMAINS: readonly string[] = [
	// ── Keluarga Mailinator ──
	'mailinator.com',
	'mailinator.net',
	'mailinator2.com',
	'reallymymail.com',
	'sogetthis.com',
	'spamherelots.com',
	'suremail.info',
	'thisisnotmyrealemail.com',
	'zippymail.info',

	// ── Guerrilla Mail ──
	'guerrillamail.com',
	'guerrillamail.net',
	'guerrillamail.org',
	'guerrillamail.biz',
	'guerrillamail.de',
	'guerrillamailblock.com',
	'grr.la',
	'sharklasers.com',
	'spam4.me',
	'pokemail.net',

	// ── 10 Minute Mail & sejenisnya ──
	'10minutemail.com',
	'10minutemail.net',
	'10minutemail.co.za',
	'10minemail.com',
	'20minutemail.com',
	'20minutemail.it',
	'30minutemail.com',
	'60minutemail.com',
	'minutemail.com',
	'tempmailer.com',
	'temp-mail.org',
	'temp-mail.io',
	'temp-mail.ru',
	'tempmail.net',
	'tempmail.com',
	'tempmail.dev',
	'tempmail.plus',
	'tempmailo.com',
	'tempail.com',
	'tmail.ws',
	'tmails.net',
	'tmpmail.org',
	'tmpmail.net',
	'tmpeml.com',
	'moakt.com',
	'moakt.ws',
	'moakt.cc',
	'disposablemail.com',
	'throwawaymail.com',
	'trashmail.com',
	'trashmail.de',
	'trashmail.me',
	'trashmail.net',
	'trash-mail.com',
	'trash-mail.de',
	'wegwerfmail.de',
	'wegwerfmail.net',
	'wegwerfmail.org',

	// ── YOPmail ──
	'yopmail.com',
	'yopmail.net',
	'yopmail.fr',
	'cool.fr.nf',
	'jetable.fr.nf',
	'nospam.ze.tc',
	'nomail.xl.cx',
	'mega.zik.dj',
	'speed.1s.fr',
	'courriel.fr.nf',
	'moncourrier.fr.nf',
	'monemail.fr.nf',
	'monmail.fr.nf',

	// ── Layanan populer lain ──
	'mailnesia.com',
	'maildrop.cc',
	'mailcatch.com',
	'mailmetrash.com',
	'mailtothis.com',
	'mytrashmail.com',
	'mt2015.com',
	'mt2014.com',
	'thankyou2010.com',
	'fakeinbox.com',
	'fakemailgenerator.com',
	'fakemail.net',
	'dispostable.com',
	'discard.email',
	'discardmail.com',
	'discardmail.de',
	'spambog.com',
	'spambog.de',
	'spambog.ru',
	'spamgourmet.com',
	'spamex.com',
	'spamfree24.org',
	'spamfree24.de',
	'spam.la',
	'binkmail.com',
	'bobmail.info',
	'chammy.info',
	'devnullmail.com',
	'letthemeatspam.com',
	'mailin8r.com',
	'notmailinator.com',
	'safetymail.info',
	'sendspamhere.com',
	'veryrealemail.com',
	'getairmail.com',
	'getnada.com',
	'nada.email',
	'inboxbear.com',
	'inboxkitten.com',
	'burnermail.io',
	'emailondeck.com',
	'email-fake.com',
	'emailfake.com',
	'fakermail.com',
	'generator.email',
	'gomail.in',
	'harakirimail.com',
	'incognitomail.com',
	'incognitomail.org',
	'jetable.org',
	'kurzepost.de',
	'link2mail.net',
	'lroid.com',
	'mail-temporaire.fr',
	'mail7.io',
	'mailbidon.com',
	'mailde.de',
	'maileater.com',
	'mailexpire.com',
	'mailforspam.com',
	'mailfreeonline.com',
	'mailguard.me',
	'mailimate.com',
	'mailnull.com',
	'mailquack.com',
	'mailsac.com',
	'mailseal.de',
	'mailslapping.com',
	'mailzilla.com',
	'meltmail.com',
	'mintemail.com',
	'mohmal.com',
	'mvrht.com',
	'myspamless.com',
	'nowmymail.com',
	'objectmail.com',
	'onewaymail.com',
	'owlymail.com',
	'proxymail.eu',
	'rcpt.at',
	'recyclemail.dk',
	'rtrtr.com',
	'shortmail.net',
	'sneakemail.com',
	'snkmail.com',
	'sofort-mail.de',
	'squizzy.de',
	'supergreatmail.com',
	'tafmail.com',
	'teleworm.us',
	'tilien.com',
	'tittbit.in',
	'tradermail.info',
	'venompen.com',
	'viditag.com',
	'walkmail.net',
	'wh4f.org',
	'willhackforfood.biz',
	'wuzup.net',
	'xagloo.com',
	'zoemail.com',
	'1secmail.com',
	'1secmail.net',
	'1secmail.org',
	'dropmail.me',
	'emltmp.com',
	'etempmail.net',
	'flurred.com',
	'linshiyouxiang.net',
	'luxusmail.org',
	'mailbox92.biz',
	'mailpoof.com',
	'mailtemp.info',
	'mailtemporaire.fr',
	'ohi.tw',
	'smashmail.de',
	'tempinbox.com',
	'tempmail2.com',
	'tempsky.com',
	'vmailpro.net',
	'yoggm.com',
];
